#! /bin/sh
printf "Do you want to install dwm? [Y/n] " && read -r prom
[ "$prom" = "n" ] && echo "Nothing will be installed" && exit 0

# aur helper
sudo pacman -S --noconfirm git base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -fsir
cd

sudo pacman -S --noconfirm xorg-xinit xorg-server xorg-xrandr xorg-xsetroot xorg-xinput vim libx11 libxinerama zsh webkit2gtk picom ttf-roboto-mono dash sxhkd alacritty light pamixer xwallpaper ttf-jetbrains-mono ttf-roboto-mono noto-fonts-emoji 


sudo usermod -a -G video "$USER" && printf "\nUser added to video group\n\n"

git clone --depth=1 https://github.com/sakibulxyz/dotfiles ~/dotfiles
cp ~/dotfiles/.??* ~/
mkdir -p ~/.config
cp -r ~/dotfiles/.config/* ~/.config/
rm -rf ~/dotfiles

dwm_ins() {
	yay -S libxft-bgra

	mkdir -p .local/src
	git clone --depth=1 https://github.com/sakibulxyz/dwm ~/.local/src/dwm
	sudo make -C ~/.local/src/dwm install

	git clone --depth=1 https://github.com/sakibulxyz/st ~/.local/src/st
	sudo make -C ~/.local/src/st install
	
	printf "Do you want to install mira mono (bangla) font? [y/N]"  && read -r font_p
	[ "$font_p" != y ] && sudo cp res/Mitra.ttf /usr/share/fonts/TTF/Mitra3.ttf

	git clone --depth=1 https://github.com/sakibulxyz/dmenu ~/.local/src/dmenu
	sudo make -C ~/.local/src/dmenu install

	git clone --depth=1 https://github.com/sakibulxyz/dwmblocks ~/.local/src/dwmblocks
	sudo make -C ~/.local/src/dwmblocks install
}

git clone --depth=1 https://github.com/sakibulxyz/bin ~/.local/bin && printf "\nbin moved to .local/bin\n"


# creating some dir
mkdir dox pix down code vids di

link_sh_dash() {
	sudo ln -sfT /bin/dash /bin/sh
	printf "[Trigger]\nType = Package\nOperation = Install\nOperation = Upgrade\nTarget = bash\n\n[Action]\nDescription = Re-pointing /bin/sh symlink to dash...\nWhen = PostTransaction\nExec = /usr/bin/ln -sfT dash /usr/bin/sh\nDepends = dash\n" | sudo tee /usr/share/libalpm/hooks/bash-to-dash-update.hook
}
ink_sh_dash

# installing font
font_ins() {
	yay -S ttf-freebanglafont
	sudo cp res/KFGQPC_Uthman_Taha_Naskh_Regular.ttf /usr/share/fonts/TTF/KFGQPC_Uthman_Taha_Naskh_Regular.ttf
}
font_ins


# android file transfer
echo "installing android file transfer utils"
sudo pacman -S --noconfirm mtpfs
yay -s jmtpfs
sudo pacman -S --noconfirm gvfs-mtp
sudo pacman -Sy --noconfirm gvfs-gphoto2

printf "Do you want to use bluetooth? [Y/n] " && read -r pr

if [ "$pr" != "n" ]
then
	sudo pacman -S --noconfirm bluez bluez-utils pulseaudio-bluetooth
	sudo systemctl start bluetooth.service
	sudo systemctl enable bluetooth.service
	bluetoothctl default-agent
	bluetoothctl agent on
fi


printf "Do you want to Install personal programs? [Y/n] " && read -r pr
if [ "$pr" != "n" ]
then
	sudo pacman -S --noconfirm adobe-source-sans-fonts wget dunst redshift zsh-syntax-highlighting jq gnome-themes-extra zip unzip bat fzf htop lxappearance maim man-db mpv neofetch neovim  sxiv syncthing termdown ueberzug xclip yt-dlp zathura zathura-cb zathura-pdf-poppler 
fi

printf "\nReplace\t $USER:x:1000:1000::/home/$USER:/bin/bash \nto\t $USER:x:1000:1000::/home/$USER:/bin/zsh \nAt\t /etc/passwd\nrun\t $ sudo vim /etc/passwd\nEdit\t wq\!\n"
