#! /bin/sh
printf "Do you want to install dwm? [Y/n] " && read -r prom
[ "$prom" = "n" ] && echo "Nothing will be installed" && exit 0

# aur helper
sudo pacman -S --noconfirm go
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -fsi
cd

sudo pacman -S --noconfirm xorg-xinit xorg-server xorg-xrandr xorg-xsetroot base-devel git vim libx11 libxinerama webkit2gtk picom ttf-roboto-mono
sudo pacman -S --noconfirm chromium dunst sxhkd redshift alacritty light pamixer xwallpaper zsh zsh-syntax-highlighting jq ttf-jetbrains-mono ttf-roboto-mono noto-fonts-emoji


yay -S libxft-bgra

sudo usermod -a -G video "$USER" && printf "\nUser added to video group\n\n"

git clone --depth=1 https://github.com/sakibulxyz/dotfiles ~/dotfiles
cp ~/dotfiles/.??* ~/
mkdir -p ~/.config
cp -r ~/dotfiles/.config/* ~/.config/
rm -rf ~/dotfiles

mkdir -p .local/src
git clone --depth=1 https://github.com/sakibulxyz/dwm ~/.local/src/dwm
sudo make -C ~/.local/src/dwm install

git clone --depth=1 https://git.suckless.org/st ~/st
sudo make -C ~/st install
rm -rf ~/st
git clone --depth=1 https://github.com/sakibulxyz/st ~/.local/src/st

git clone --depth=1 https://github.com/sakibulxyz/dmenu ~/.local/src/dmenu
sudo make -C ~/.local/src/dmenu install

git clone --depth=1 https://github.com/sakibulxyz/dwmblocks ~/.local/src/dwmblocks
sudo make -C ~/.local/src/dwmblocks install

git clone --depth=1 https://github.com/sakibulxyz/bin ~/.local/bin && printf "\nbin moved to .local/bin\n"

yay -S ttf-freebanglafont

mkdir dox pix dl code vids di


printf "Do you wanna install Personal pks? [Y/n] " && read -r prom
if [ ! "$prom" = "n" ] 
then
	sudo pacman -S --noconfirm bat fzf htop jq lxappearance maim man-db mpv nautilus neofetch neovim python-pywal sxiv syncthing termdown ueberzug xclip yt-dlp zathura zathura-cb zathura-pdf-poppler bluez bluez-utils pulseaudio-bluetooth
fi

printf "\033[1;31minstall patched st by uur self \033[0m\n\t $ cd ~/.local/src/st\n\t $ sudo fakeroot\n\t $ make install \n\t $ exit\n\n" 
printf "\nReplace\t $USER:x:1000:1000::/home/$USER:/bin/bash \nto\t $USER:x:1000:1000::/home/$USER:/bin/zsh \nAt\t /etc/passwd\nrun\t $ sudo vim /etc/passwd\nEdit\t wq\!\n"
