#! /bin/sh
printf "Do you want to install dwm? [Y/n] " && read -r prom
[ "$prom" = "n" ] && echo "Nothing will be installed" && exit 0

# aur helper
sudo pacman -S --noconfirm go base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -fsi
cd

sudo pacman -S --noconfirm xorg-xinit xorg-server xorg-xrandr xorg-xsetroot xorg-xinput vim libx11 libxinerama zsh webkit2gtk picom ttf-roboto-mono
sudo pacman -S --noconfirm dash wget noto-fonts dunst sxhkd redshift alacritty light pamixer xwallpaper zsh-syntax-highlighting jq ttf-jetbrains-mono ttf-roboto-mono noto-fonts-emoji gnome-themes-extra

yay -S libxft-bgra

sudo usermod -a -G video "$USER" && printf "\nUser added to video group\n\n"

git clone --depth=1 https://github.com/sakibulxyz/dotfiles ~/dotfiles
cp ~/dotfiles/.??* ~/
mkdir -p ~/.config
cp -r ~/dotfiles/.config/* ~/.config/
rm -rf ~/dotfiles

mkdir -p .local/src
git clone --depth=1 https://github.com/sakibulxyz/dwm ~/.local/src/dwm
sudo make -C ~/.local/src/dwm install

git clone --depth=1 https://git.suckless.org/st ~/st
git clone --depth=1 https://github.com/sakibulxyz/st ~/.local/src/st
sudo make -C ~/.local/src/st install || sudo make -C ~/st install && simplet="1"
rm -rf ~/st

git clone --depth=1 https://github.com/sakibulxyz/dmenu ~/.local/src/dmenu
sudo make -C ~/.local/src/dmenu install

git clone --depth=1 https://github.com/sakibulxyz/dwmblocks ~/.local/src/dwmblocks
sudo make -C ~/.local/src/dwmblocks install

git clone --depth=1 https://github.com/sakibulxyz/bin ~/.local/bin && printf "\nbin moved to .local/bin\n"

# coping Bangla Mono font for st
sudo cp res/Mitra.ttf /usr/share/fonts/TTF/Mitra3.ttf
# installing bangla font
yay -S ttf-freebanglafont

# creating some dir
mkdir dox pix down code vids di

# installing addictional pkgs
sudo pacman -S --noconfirm zip unzip bat fzf htop lxappearance maim man-db mpv nautilus neofetch neovim python-pywal sxiv syncthing termdown ueberzug xclip yt-dlp zathura zathura-cb zathura-pdf-poppler bluez bluez-utils pulseaudio-bluetooth

# linking sh to dash
sudo ln -sfT /bin/dash /bin/sh
printf "[Trigger]\nType = Package\nOperation = Install\nOperation = Upgrade\nTarget = bash\n\n[Action]\nDescription = Re-pointing /bin/sh symlink to dash...\nWhen = PostTransaction\nExec = /usr/bin/ln -sfT dash /usr/bin/sh\nDepends = dash\n" | sudo tee /usr/share/libalpm/hooks/bash-to-dash-update.hook

# android file transfer
echo "installing android file transfer utils"
sudo pacman -S --noconfirm mtpfs
yay -s jmtpfs
sudo pacman -S --noconfirm gvfs-mtp
sudo pacman -Sy --noconfirm gvfs-gphoto2

[ "$simplet" = "1" ] && printf "\033[1;31minstall patched st by uur self \033[0m\n\t $ cd ~/.local/src/st\n\t $ sudo fakeroot\n\t $ make install \n\t $ exit\n\n"

printf "\nReplace\t $USER:x:1000:1000::/home/$USER:/bin/bash \nto\t $USER:x:1000:1000::/home/$USER:/bin/zsh \nAt\t /etc/passwd\nrun\t $ sudo vim /etc/passwd\nEdit\t wq\!\n"
